FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build arguments for public env vars (set at build time)
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WIDGET_API_KEY
ARG NEXT_PUBLIC_WIDGET_CHATBOT_ID
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WIDGET_API_KEY=$NEXT_PUBLIC_WIDGET_API_KEY
ENV NEXT_PUBLIC_WIDGET_CHATBOT_ID=$NEXT_PUBLIC_WIDGET_CHATBOT_ID

RUN npm run build

ENV PORT=3000
EXPOSE 3000

CMD ["npm", "start"]
